# Generated by Django 4.1.2 on 2022-11-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=25, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='mobile')),
                ('company_name', models.CharField(max_length=250, unique=True, verbose_name='company name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('SUCCESS', 'SUCCESS')], default='IN_PROGRESS', max_length=50, verbose_name='status')),
            ],
        ),
    ]
