# Generated by Django 4.1.2 on 2022-10-20 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=25, verbose_name='last name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='mobile')),
                ('company_name', models.CharField(max_length=250, verbose_name='company name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('SUCCESS', 'SUCCESS')], default='IN_PROGRESS', max_length=50, verbose_name='status')),
                ('sales_contact', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'USER_SALES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
